/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as MyPageIndexImport } from "./routes/my-page/index";
import { Route as MyKiwisIndexImport } from "./routes/my-kiwis/index";
import { Route as KiwiIdImport } from "./routes/kiwi/$id";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const MyPageIndexRoute = MyPageIndexImport.update({
  id: "/my-page/",
  path: "/my-page/",
  getParentRoute: () => rootRoute,
} as any);

const MyKiwisIndexRoute = MyKiwisIndexImport.update({
  id: "/my-kiwis/",
  path: "/my-kiwis/",
  getParentRoute: () => rootRoute,
} as any);

const KiwiIdRoute = KiwiIdImport.update({
  id: "/kiwi/$id",
  path: "/kiwi/$id",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/kiwi/$id": {
      id: "/kiwi/$id";
      path: "/kiwi/$id";
      fullPath: "/kiwi/$id";
      preLoaderRoute: typeof KiwiIdImport;
      parentRoute: typeof rootRoute;
    };
    "/my-kiwis/": {
      id: "/my-kiwis/";
      path: "/my-kiwis";
      fullPath: "/my-kiwis";
      preLoaderRoute: typeof MyKiwisIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/my-page/": {
      id: "/my-page/";
      path: "/my-page";
      fullPath: "/my-page";
      preLoaderRoute: typeof MyPageIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/kiwi/$id": typeof KiwiIdRoute;
  "/my-kiwis": typeof MyKiwisIndexRoute;
  "/my-page": typeof MyPageIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/kiwi/$id": typeof KiwiIdRoute;
  "/my-kiwis": typeof MyKiwisIndexRoute;
  "/my-page": typeof MyPageIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/kiwi/$id": typeof KiwiIdRoute;
  "/my-kiwis/": typeof MyKiwisIndexRoute;
  "/my-page/": typeof MyPageIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/kiwi/$id" | "/my-kiwis" | "/my-page";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/kiwi/$id" | "/my-kiwis" | "/my-page";
  id: "__root__" | "/" | "/kiwi/$id" | "/my-kiwis/" | "/my-page/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  KiwiIdRoute: typeof KiwiIdRoute;
  MyKiwisIndexRoute: typeof MyKiwisIndexRoute;
  MyPageIndexRoute: typeof MyPageIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KiwiIdRoute: KiwiIdRoute,
  MyKiwisIndexRoute: MyKiwisIndexRoute,
  MyPageIndexRoute: MyPageIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/kiwi/$id",
        "/my-kiwis/",
        "/my-page/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/kiwi/$id": {
      "filePath": "kiwi/$id.tsx"
    },
    "/my-kiwis/": {
      "filePath": "my-kiwis/index.tsx"
    },
    "/my-page/": {
      "filePath": "my-page/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
