// 더미 데이터 배열
const kiwis = [
  {
    id: "1",
    name: "데미안 읽는 방",
    description: "알을 깨고 나와 봅시다",
    image: "/images/demian.jpg",
    lastActivityAt: "1시간 전",
    detailDescription:
      "헤르만 헤세의 대표작 '데미안'을 함께 읽고 토론하는 모임입니다. 우리는 매주 일정 분량을 읽고 작품의 상징성, 캐릭터 분석, 그리고 현대적 해석에 대해 토론합니다. 책을 통해 자아 발견의 여정을 함께 나눕시다.",
    isEncrypted: false,
    memberCount: 12,
    progress: 75,
    book: {
      title: "데미안",
      author: "헤르만 헤세",
      cover: "/images/demian.jpg",
    },
    discussions: [
      {
        id: "101",
        title: "데미안에서 신카이 아베의 역할",
        comments: 12,
        lastActive: "어제",
      },
      {
        id: "102",
        title: "소설의 상징성에 대한 토론",
        comments: 8,
        lastActive: "3일 전",
      },
      {
        id: "103",
        title: "여러분이 생각하는 책의 주제는?",
        comments: 15,
        lastActive: "1주일 전",
      },
    ],
    events: [
      {
        id: "201",
        title: "작가와의 만남",
        date: "2023년 6월 15일",
        time: "오후 7시",
        participants: 8,
      },
      {
        id: "202",
        title: "1부 완독 토론회",
        date: "2023년 6월 20일",
        time: "오후 8시",
        participants: 12,
      },
    ],
    activities: [
      {
        id: "301",
        user: "김하늘",
        action: "새 메모를 추가했습니다",
        content: "42쪽: 인상 깊은 문장 발견!",
        time: "1시간 전",
      },
      {
        id: "302",
        user: "이태양",
        action: "토론에 댓글을 남겼습니다",
        content: "저도 그 부분이 매우 인상적이었어요",
        time: "3시간 전",
      },
      {
        id: "303",
        user: "박별",
        action: "새 챕터를 완료했습니다",
        content: "3장: 어둠 속의 빛",
        time: "어제",
      },
    ],
    createdAt: "2023년 5월 10일",
    admin: "김독서",
  },
  {
    id: "2",
    name: "해리포터 독서모임",
    description: "마법의 세계로 함께 떠나요",
    image: "/images/harry-potter.jpg",
    lastActivityAt: "30분 전",
    detailDescription:
      "J.K. 롤링의 해리포터 시리즈를 함께 읽고 마법 세계의 모험을 나누는 모임입니다. 호그와트의 기숙사 분류부터 주문 연습까지, 마법 세계의 모든 것을 탐험합니다. 머글이든 마법사든 모두 환영합니다!",
    isEncrypted: false,
    memberCount: 24,
    progress: 60,
    book: {
      title: "해리포터와 마법사의 돌",
      author: "J.K. 롤링",
      cover: "/images/harry-potter.jpg",
    },
    discussions: [
      {
        id: "111",
        title: "해리와 말포이의 관계 분석",
        comments: 32,
        lastActive: "어제",
      },
      {
        id: "112",
        title: "스네이프 교수는 선한가, 악한가?",
        comments: 45,
        lastActive: "2일 전",
      },
      {
        id: "113",
        title: "마법 세계의 정치 시스템",
        comments: 18,
        lastActive: "4일 전",
      },
    ],
    events: [
      {
        id: "211",
        title: "호그와트 기숙사 분류 퀴즈 이벤트",
        date: "2023년 6월 25일",
        time: "오후 6시",
        participants: 20,
      },
    ],
    activities: [
      {
        id: "311",
        user: "위즐리",
        action: "질문을 게시했습니다",
        content: "덤블도어의 정체에 대한 의견이 궁금합니다",
        time: "30분 전",
      },
      {
        id: "312",
        user: "그레인저",
        action: "퀴즈 결과를 공유했습니다",
        content: "그리핀도르 기숙사에 배정받았어요!",
        time: "2시간 전",
      },
    ],
    createdAt: "2023년 1월 15일",
    admin: "해리",
  },
  {
    id: "3",
    name: "코스모스 스터디",
    description: "우주의 신비를 탐험합니다",
    image: "/images/cosmos.jpg",
    lastActivityAt: "어제",
    detailDescription:
      "칼 세이건의 '코스모스'를 중심으로 우주와 과학에 대해 함께 공부하는 그룹입니다. 복잡한 우주 개념을 함께 이해하고, 과학적 사고를 넓히는 것이 목표입니다. 천문학, 물리학, 생물학 등 다양한 과학 분야에 관심 있는 분들을 환영합니다.",
    isEncrypted: true,
    memberCount: 8,
    progress: 40,
    book: {
      title: "코스모스",
      author: "칼 세이건",
      cover: "/images/cosmos.jpg",
    },
    discussions: [
      {
        id: "121",
        title: "우주의 기원과 빅뱅 이론",
        comments: 24,
        lastActive: "어제",
      },
      {
        id: "122",
        title: "외계 생명체의 존재 가능성",
        comments: 36,
        lastActive: "3일 전",
      },
    ],
    events: [
      {
        id: "221",
        title: "천문대 방문",
        date: "2023년 7월 5일",
        time: "오후 8시",
        participants: 7,
      },
    ],
    activities: [
      {
        id: "321",
        user: "김우주",
        action: "새 자료를 공유했습니다",
        content: "NASA에서 발표한 최신 우주 관측 결과입니다",
        time: "어제",
      },
      {
        id: "322",
        user: "박별",
        action: "질문을 남겼습니다",
        content: "상대성 이론에 대해 더 자세히 알고 싶어요",
        time: "3일 전",
      },
    ],
    createdAt: "2023년 3월 21일",
    admin: "이칼세이건",
  },
  {
    id: "4",
    name: "소설 작가 모임",
    description: "함께 소설을 쓰고 공유해요",
    image: "/images/demian.png",
    lastActivityAt: "2일 전",
    detailDescription:
      "소설 창작에 관심 있는 사람들의 모임입니다. 매주 각자의 작품을 공유하고 피드백을 주고받으며 함께 성장합니다. 단편소설, 장편소설, 시나리오 등 다양한 창작물을 환영합니다. 초보자부터 경험자까지 모두 참여할 수 있습니다.",
    isEncrypted: false,
    memberCount: 15,
    progress: 50,
    book: {
      title: "소설 쓰기의 모든 것",
      author: "제임스 스콧 벨",
      cover: "/images/writing.jpg",
    },
    discussions: [
      {
        id: "131",
        title: "효과적인 캐릭터 구축 방법",
        comments: 22,
        lastActive: "2일 전",
      },
      {
        id: "132",
        title: "플롯 구성의 비결",
        comments: 19,
        lastActive: "5일 전",
      },
    ],
    events: [
      {
        id: "231",
        title: "작품 발표회",
        date: "2023년 6월 30일",
        time: "오후 3시",
        participants: 12,
      },
    ],
    activities: [
      {
        id: "331",
        user: "이야기꾼",
        action: "새 단편을 게시했습니다",
        content: "제 신작 '별빛 아래'를 공유합니다",
        time: "2일 전",
      },
      {
        id: "332",
        user: "김작가",
        action: "피드백을 남겼습니다",
        content: "도입부가 정말 흥미롭네요!",
        time: "2일 전",
      },
    ],
    createdAt: "2023년 2월 10일",
    admin: "박소설",
  },
  {
    id: "5",
    name: "시 낭독회",
    description: "아름다운 시를 함께 읽어요",
    image: "/images/poem.jpg",
    lastActivityAt: "지난주",
    detailDescription:
      "시를 사랑하는 사람들이 모여 다양한 시를 읽고 감상을 나누는 모임입니다. 한국 현대시부터 세계 고전시까지, 시간과 공간을 초월한 아름다운 시의 세계를 함께 탐험합니다. 매주 새로운 시인의 작품을 선정하여 깊이 있게 탐구합니다.",
    isEncrypted: false,
    memberCount: 10,
    progress: 80,
    book: { title: "윤동주 전집", author: "윤동주", cover: "/images/yoon.jpg" },
    discussions: [
      {
        id: "141",
        title: "윤동주의 '서시'에 담긴 의미",
        comments: 15,
        lastActive: "지난주",
      },
      {
        id: "142",
        title: "현대시의 이미지와 은유",
        comments: 12,
        lastActive: "2주 전",
      },
    ],
    events: [
      {
        id: "241",
        title: "봄 시 낭독회",
        date: "2023년 6월 10일",
        time: "오후 5시",
        participants: 10,
      },
    ],
    activities: [
      {
        id: "341",
        user: "이시인",
        action: "새 시를 추천했습니다",
        content: "파블로 네루다의 '스무 편의 사랑의 시와 한 편의 절망의 노래'",
        time: "지난주",
      },
      {
        id: "342",
        user: "김서정",
        action: "감상을 공유했습니다",
        content: "이 시의 마지막 연이 정말 가슴에 와닿네요",
        time: "2주 전",
      },
    ],
    createdAt: "2022년 12월 5일",
    admin: "정시인",
  },
];
export default kiwis;
